# ********************************
# Transmitter targets
# ********************************

# ESP32 S3
[env:Unified_ESP32S3_TX]
extends = env_common_esp32s3tx
build_flags =
	${env_common_esp32s3tx.build_flags}
	${common_env_data.build_flags_tx}
	-include target/Unified_ESP32_TX.h
	-D VTABLES_IN_FLASH=1
	-O2
build_src_filter = ${env_common_esp32s3tx.build_src_filter} -<rx_*.cpp> -<rx-*/>
lib_deps =
    ${env_common_esp32s3tx.tft_lib_deps}
    ${env_common_esp32s3tx.oled_lib_deps}
	SPIFFS
upload_speed = 460800
monitor_speed = 420000
debug_tool = esp-builtin
debug_init_break = break setup
; 如果你要启用 USB-JTAG，需要打开以下串口配置
upload_protocol = esp-builtin

[env:Unified_ESP32S3XIAO_TX]
extends = env_common_esp32s3tx
build_flags =
	${env_common_esp32s3tx.build_flags}
	${common_env_data.build_flags_tx}
	-include target/Unified_ESP32_TX.h
	-D VTABLES_IN_FLASH=1
	-O2
build_src_filter = ${env_common_esp32s3tx.build_src_filter} -<rx_*.cpp> -<rx-*/>
lib_deps =
    ${env_common_esp32s3tx.tft_lib_deps}
    ${env_common_esp32s3tx.oled_lib_deps}
	SPIFFS
upload_speed = 460800
monitor_speed = 420000
























